class ErrorCode:
    PERSONA_NO_ENCONTRADA = "La persona no fue encontrada."
    MASCOTA_NO_ENCONTRADA = "La mascota no fue encontrada."
    VEHICULO_NO_ENCONTRADA = "La vehiculo no fue encontrada."
    EMAIL_DUPLICADO = "El email ya existe."
    NOMBRE_DUPLICADO = "El nombre ya existe."
    PERSONA_TIENE_MASCOTAS = "La persona tiene mascotas a cargo. No puede ser eliminada."
    PERSONA_TIENE_VEHICULO = "La persona tiene vehiculos a cargo. No puede ser eliminada."
    TIPO_MASCOTA_INVALIDO = "El tipo de mascota indicado es inválido. El valor indicado debiera ser una de las opciones en la lista:"
    TIPO_VEHICULO_INVALIDO = "El tipo de vehiculo indicado es inválido. El valor indicado debiera ser una de las opciones en la lista:"